version: '3'
services:
  app:
    container_name: grocery_list_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:80
      - 5173:5173
    volumes:
      - .:/var/www/html/grocery_list_app
    #network_mode: "host"
    environment:
      - UID=${UID}
      - GID=${GID}
    

